name: "sales_warehouse"
version: "1.0.5"
config-version: 2

profile: "sales_warehouse"

model-paths: ["models"]
test-paths: ["tests"]

models:
  sales_warehouse:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
