name: "sales_warehouse"
version: "1.0.1"
description: "Sales warehouse dbt project (thesis CI/CD)"
config-version: 2

profile: "sales_warehouse"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  sales_warehouse:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
