name: "sales_warehouse"
version: "1.0.5"
config-version: 2

profile: "sales_warehouse"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

seeds:
  sales_warehouse:
    +schema: raw

models:
  sales_warehouse:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
